function [corrected,raw]=merge_ptCloud_tf(ptCLoudA,ptCloudB,tf,gridStep)

if nargin<4
    gridStep = 0.1;
end

rot = tf{1}.Transforms.Transform.Rotation;
trans = tf{1}.Transforms.Transform.Translation;
trans = [trans.X trans.Y trans.Z];

trans = [1 0 0 0;...
    0 1 0 0;...
    0 0 1 0;...
    trans 1];
rotX = [1      0          0  0;...
    0  cos(rot.X) sin(rot.X) 0;...
    0 -sin(rot.X) cos(rot.X) 0;...
    0          0          0  1];
rotY = [cos(rot.Y) 0 -sin(rot.Y) 0;...
    0          1          0  0;...
    sin(rot.Y) 0  cos(rot.Y) 0;...
    0          0          0  1];
rotZ = [cos(rot.Y) sin(rot.Y) 0 0;...
    -sin(rot.Y) cos(rot.Y) 0  0;...
    0                   0  1  0;...
    0                   0  0  1];

A = trans * rotX * rotY * rotZ;
tform = affine3d(A);
aligned = pctransform(ptCloudB,tform);

raw = pcmerge(ptCLoudA, ptCloudB, gridStep);
corrected = pcmerge(ptCLoudA, aligned, gridStep);

end

